site_name: "mob-design-system-android"
site_description: "Biblioteca para centralizar a estratégia de tokens e temas do Localiza Design System para Android."

nav:
  - Início Rápido: 'index.md'
  - Features:
      - Cores: 'features/color.md'
      - Espaçamento : 'features/spacing.md'
      - Temas: 'features/themes.md'
  - Releases:
      - v.0.1.0: 'releases/v.0.1.0.md'
      - v.0.0.1: 'releases/v.0.0.1.md'
plugins:
  - techdocs-core

